package com.crm.controller;

import com.crm.dao.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

/**
 * Created by prashu on 27/8/17.
 */
@Controller
@RequestMapping(path="/login")
public class LoginController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;
    @GetMapping(path = "/user")
    public @ResponseBody
    String getUser(@RequestParam String email){
        return userRepository.findByEmail(email).getEmail();
    }

}
